/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import com.baloise.open.strava.client.model.SummaryClubDto;
import com.baloise.open.strava.client.model.SummaryGearDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DetailedAthleteAllOfDto
 */
public class DetailedAthleteAllOfDtoTest {
    private final DetailedAthleteAllOfDto model = new DetailedAthleteAllOfDto();

    /**
     * Model tests for DetailedAthleteAllOfDto
     */
    @Test
    public void testDetailedAthleteAllOfDto() {
        // TODO: test DetailedAthleteAllOfDto
    }

    /**
     * Test the property 'followerCount'
     */
    @Test
    public void followerCountTest() {
        // TODO: test followerCount
    }

    /**
     * Test the property 'friendCount'
     */
    @Test
    public void friendCountTest() {
        // TODO: test friendCount
    }

    /**
     * Test the property 'measurementPreference'
     */
    @Test
    public void measurementPreferenceTest() {
        // TODO: test measurementPreference
    }

    /**
     * Test the property 'ftp'
     */
    @Test
    public void ftpTest() {
        // TODO: test ftp
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'clubs'
     */
    @Test
    public void clubsTest() {
        // TODO: test clubs
    }

    /**
     * Test the property 'bikes'
     */
    @Test
    public void bikesTest() {
        // TODO: test bikes
    }

    /**
     * Test the property 'shoes'
     */
    @Test
    public void shoesTest() {
        // TODO: test shoes
    }

}
