/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import com.baloise.open.strava.client.model.PolylineMapDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DetailedSegmentAllOfDto
 */
public class DetailedSegmentAllOfDtoTest {
    private final DetailedSegmentAllOfDto model = new DetailedSegmentAllOfDto();

    /**
     * Model tests for DetailedSegmentAllOfDto
     */
    @Test
    public void testDetailedSegmentAllOfDto() {
        // TODO: test DetailedSegmentAllOfDto
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'totalElevationGain'
     */
    @Test
    public void totalElevationGainTest() {
        // TODO: test totalElevationGain
    }

    /**
     * Test the property 'map'
     */
    @Test
    public void mapTest() {
        // TODO: test map
    }

    /**
     * Test the property 'effortCount'
     */
    @Test
    public void effortCountTest() {
        // TODO: test effortCount
    }

    /**
     * Test the property 'athleteCount'
     */
    @Test
    public void athleteCountTest() {
        // TODO: test athleteCount
    }

    /**
     * Test the property 'hazardous'
     */
    @Test
    public void hazardousTest() {
        // TODO: test hazardous
    }

    /**
     * Test the property 'starCount'
     */
    @Test
    public void starCountTest() {
        // TODO: test starCount
    }

}
