/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import com.baloise.open.strava.client.model.DetailedSegmentAllOfDto;
import com.baloise.open.strava.client.model.PolylineMapDto;
import com.baloise.open.strava.client.model.SummaryPRSegmentEffortDto;
import com.baloise.open.strava.client.model.SummarySegmentDto;
import com.baloise.open.strava.client.model.SummarySegmentEffortDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DetailedSegmentDto
 */
public class DetailedSegmentDtoTest {
    private final DetailedSegmentDto model = new DetailedSegmentDto();

    /**
     * Model tests for DetailedSegmentDto
     */
    @Test
    public void testDetailedSegmentDto() {
        // TODO: test DetailedSegmentDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'activityType'
     */
    @Test
    public void activityTypeTest() {
        // TODO: test activityType
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'averageGrade'
     */
    @Test
    public void averageGradeTest() {
        // TODO: test averageGrade
    }

    /**
     * Test the property 'maximumGrade'
     */
    @Test
    public void maximumGradeTest() {
        // TODO: test maximumGrade
    }

    /**
     * Test the property 'elevationHigh'
     */
    @Test
    public void elevationHighTest() {
        // TODO: test elevationHigh
    }

    /**
     * Test the property 'elevationLow'
     */
    @Test
    public void elevationLowTest() {
        // TODO: test elevationLow
    }

    /**
     * Test the property 'startLatlng'
     */
    @Test
    public void startLatlngTest() {
        // TODO: test startLatlng
    }

    /**
     * Test the property 'endLatlng'
     */
    @Test
    public void endLatlngTest() {
        // TODO: test endLatlng
    }

    /**
     * Test the property 'climbCategory'
     */
    @Test
    public void climbCategoryTest() {
        // TODO: test climbCategory
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property '_private'
     */
    @Test
    public void _privateTest() {
        // TODO: test _private
    }

    /**
     * Test the property 'athletePrEffort'
     */
    @Test
    public void athletePrEffortTest() {
        // TODO: test athletePrEffort
    }

    /**
     * Test the property 'athleteSegmentStats'
     */
    @Test
    public void athleteSegmentStatsTest() {
        // TODO: test athleteSegmentStats
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'totalElevationGain'
     */
    @Test
    public void totalElevationGainTest() {
        // TODO: test totalElevationGain
    }

    /**
     * Test the property 'map'
     */
    @Test
    public void mapTest() {
        // TODO: test map
    }

    /**
     * Test the property 'effortCount'
     */
    @Test
    public void effortCountTest() {
        // TODO: test effortCount
    }

    /**
     * Test the property 'athleteCount'
     */
    @Test
    public void athleteCountTest() {
        // TODO: test athleteCount
    }

    /**
     * Test the property 'hazardous'
     */
    @Test
    public void hazardousTest() {
        // TODO: test hazardous
    }

    /**
     * Test the property 'starCount'
     */
    @Test
    public void starCountTest() {
        // TODO: test starCount
    }

}
