/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import com.baloise.open.strava.client.model.ActivityTypeDto;
import com.baloise.open.strava.client.model.DetailedClubAllOfDto;
import com.baloise.open.strava.client.model.SummaryClubDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DetailedClubDto
 */
public class DetailedClubDtoTest {
    private final DetailedClubDto model = new DetailedClubDto();

    /**
     * Model tests for DetailedClubDto
     */
    @Test
    public void testDetailedClubDto() {
        // TODO: test DetailedClubDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'resourceState'
     */
    @Test
    public void resourceStateTest() {
        // TODO: test resourceState
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'profileMedium'
     */
    @Test
    public void profileMediumTest() {
        // TODO: test profileMedium
    }

    /**
     * Test the property 'coverPhoto'
     */
    @Test
    public void coverPhotoTest() {
        // TODO: test coverPhoto
    }

    /**
     * Test the property 'coverPhotoSmall'
     */
    @Test
    public void coverPhotoSmallTest() {
        // TODO: test coverPhotoSmall
    }

    /**
     * Test the property 'sportType'
     */
    @Test
    public void sportTypeTest() {
        // TODO: test sportType
    }

    /**
     * Test the property 'activityTypes'
     */
    @Test
    public void activityTypesTest() {
        // TODO: test activityTypes
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property '_private'
     */
    @Test
    public void _privateTest() {
        // TODO: test _private
    }

    /**
     * Test the property 'memberCount'
     */
    @Test
    public void memberCountTest() {
        // TODO: test memberCount
    }

    /**
     * Test the property 'featured'
     */
    @Test
    public void featuredTest() {
        // TODO: test featured
    }

    /**
     * Test the property 'verified'
     */
    @Test
    public void verifiedTest() {
        // TODO: test verified
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'membership'
     */
    @Test
    public void membershipTest() {
        // TODO: test membership
    }

    /**
     * Test the property 'admin'
     */
    @Test
    public void adminTest() {
        // TODO: test admin
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'followingCount'
     */
    @Test
    public void followingCountTest() {
        // TODO: test followingCount
    }

}
