/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExplorerSegmentDto
 */
public class ExplorerSegmentDtoTest {
    private final ExplorerSegmentDto model = new ExplorerSegmentDto();

    /**
     * Model tests for ExplorerSegmentDto
     */
    @Test
    public void testExplorerSegmentDto() {
        // TODO: test ExplorerSegmentDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'climbCategory'
     */
    @Test
    public void climbCategoryTest() {
        // TODO: test climbCategory
    }

    /**
     * Test the property 'climbCategoryDesc'
     */
    @Test
    public void climbCategoryDescTest() {
        // TODO: test climbCategoryDesc
    }

    /**
     * Test the property 'avgGrade'
     */
    @Test
    public void avgGradeTest() {
        // TODO: test avgGrade
    }

    /**
     * Test the property 'startLatlng'
     */
    @Test
    public void startLatlngTest() {
        // TODO: test startLatlng
    }

    /**
     * Test the property 'endLatlng'
     */
    @Test
    public void endLatlngTest() {
        // TODO: test endLatlng
    }

    /**
     * Test the property 'elevDifference'
     */
    @Test
    public void elevDifferenceTest() {
        // TODO: test elevDifference
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'points'
     */
    @Test
    public void pointsTest() {
        // TODO: test points
    }

}
