/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import com.baloise.open.strava.client.model.ZoneRangeDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HeartRateZoneRangesDto
 */
public class HeartRateZoneRangesDtoTest {
    private final HeartRateZoneRangesDto model = new HeartRateZoneRangesDto();

    /**
     * Model tests for HeartRateZoneRangesDto
     */
    @Test
    public void testHeartRateZoneRangesDto() {
        // TODO: test HeartRateZoneRangesDto
    }

    /**
     * Test the property 'customZones'
     */
    @Test
    public void customZonesTest() {
        // TODO: test customZones
    }

    /**
     * Test the property 'zones'
     */
    @Test
    public void zonesTest() {
        // TODO: test zones
    }

}
