/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SplitDto
 */
public class SplitDtoTest {
    private final SplitDto model = new SplitDto();

    /**
     * Model tests for SplitDto
     */
    @Test
    public void testSplitDto() {
        // TODO: test SplitDto
    }

    /**
     * Test the property 'averageSpeed'
     */
    @Test
    public void averageSpeedTest() {
        // TODO: test averageSpeed
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'elapsedTime'
     */
    @Test
    public void elapsedTimeTest() {
        // TODO: test elapsedTime
    }

    /**
     * Test the property 'elevationDifference'
     */
    @Test
    public void elevationDifferenceTest() {
        // TODO: test elevationDifference
    }

    /**
     * Test the property 'paceZone'
     */
    @Test
    public void paceZoneTest() {
        // TODO: test paceZone
    }

    /**
     * Test the property 'movingTime'
     */
    @Test
    public void movingTimeTest() {
        // TODO: test movingTime
    }

    /**
     * Test the property 'split'
     */
    @Test
    public void splitTest() {
        // TODO: test split
    }

}
