/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import com.baloise.open.strava.client.model.AltitudeStreamDto;
import com.baloise.open.strava.client.model.CadenceStreamDto;
import com.baloise.open.strava.client.model.DistanceStreamDto;
import com.baloise.open.strava.client.model.HeartrateStreamDto;
import com.baloise.open.strava.client.model.LatLngStreamDto;
import com.baloise.open.strava.client.model.MovingStreamDto;
import com.baloise.open.strava.client.model.PowerStreamDto;
import com.baloise.open.strava.client.model.SmoothGradeStreamDto;
import com.baloise.open.strava.client.model.SmoothVelocityStreamDto;
import com.baloise.open.strava.client.model.TemperatureStreamDto;
import com.baloise.open.strava.client.model.TimeStreamDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StreamSetDto
 */
public class StreamSetDtoTest {
    private final StreamSetDto model = new StreamSetDto();

    /**
     * Model tests for StreamSetDto
     */
    @Test
    public void testStreamSetDto() {
        // TODO: test StreamSetDto
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'latlng'
     */
    @Test
    public void latlngTest() {
        // TODO: test latlng
    }

    /**
     * Test the property 'altitude'
     */
    @Test
    public void altitudeTest() {
        // TODO: test altitude
    }

    /**
     * Test the property 'velocitySmooth'
     */
    @Test
    public void velocitySmoothTest() {
        // TODO: test velocitySmooth
    }

    /**
     * Test the property 'heartrate'
     */
    @Test
    public void heartrateTest() {
        // TODO: test heartrate
    }

    /**
     * Test the property 'cadence'
     */
    @Test
    public void cadenceTest() {
        // TODO: test cadence
    }

    /**
     * Test the property 'watts'
     */
    @Test
    public void wattsTest() {
        // TODO: test watts
    }

    /**
     * Test the property 'temp'
     */
    @Test
    public void tempTest() {
        // TODO: test temp
    }

    /**
     * Test the property 'moving'
     */
    @Test
    public void movingTest() {
        // TODO: test moving
    }

    /**
     * Test the property 'gradeSmooth'
     */
    @Test
    public void gradeSmoothTest() {
        // TODO: test gradeSmooth
    }

}
