/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import com.baloise.open.strava.client.model.ActivityTypeDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdatableActivityDto
 */
public class UpdatableActivityDtoTest {
    private final UpdatableActivityDto model = new UpdatableActivityDto();

    /**
     * Model tests for UpdatableActivityDto
     */
    @Test
    public void testUpdatableActivityDto() {
        // TODO: test UpdatableActivityDto
    }

    /**
     * Test the property 'commute'
     */
    @Test
    public void commuteTest() {
        // TODO: test commute
    }

    /**
     * Test the property 'trainer'
     */
    @Test
    public void trainerTest() {
        // TODO: test trainer
    }

    /**
     * Test the property 'hideFromHome'
     */
    @Test
    public void hideFromHomeTest() {
        // TODO: test hideFromHome
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'gearId'
     */
    @Test
    public void gearIdTest() {
        // TODO: test gearId
    }

}
