/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.api;

import com.baloise.open.strava.client.model.ActivityZoneDto;
import com.baloise.open.strava.client.model.CommentDto;
import com.baloise.open.strava.client.model.DetailedActivityDto;
import com.baloise.open.strava.client.model.FaultDto;
import com.baloise.open.strava.client.model.LapDto;
import java.time.OffsetDateTime;
import com.baloise.open.strava.client.model.SummaryActivityDto;
import com.baloise.open.strava.client.model.SummaryAthleteDto;
import com.baloise.open.strava.client.model.UpdatableActivityDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ActivitiesApi
 */
@Ignore
public class ActivitiesApiTest {

    private final ActivitiesApi api = new ActivitiesApi();

    
    /**
     * Create an Activity
     *
     * Creates a manual activity for an athlete, requires activity:write scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createActivityTest() {
        String name = null;
        String type = null;
        OffsetDateTime startDateLocal = null;
        Integer elapsedTime = null;
        String description = null;
        Float distance = null;
        Integer trainer = null;
        Integer commute = null;
        Boolean hideFromHome = null;
        DetailedActivityDto response = api.createActivity(name, type, startDateLocal, elapsedTime, description, distance, trainer, commute, hideFromHome);

        // TODO: test validations
    }
    
    /**
     * Get Activity
     *
     * Returns the given activity that is owned by the authenticated athlete. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActivityByIdTest() {
        Long id = null;
        Boolean includeAllEfforts = null;
        DetailedActivityDto response = api.getActivityById(id, includeAllEfforts);

        // TODO: test validations
    }
    
    /**
     * List Activity Comments
     *
     * Returns the comments on the given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommentsByActivityIdTest() {
        Long id = null;
        Integer page = null;
        Integer perPage = null;
        List<CommentDto> response = api.getCommentsByActivityId(id, page, perPage);

        // TODO: test validations
    }
    
    /**
     * List Activity Kudoers
     *
     * Returns the athletes who kudoed an activity identified by an identifier. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKudoersByActivityIdTest() {
        Long id = null;
        Integer page = null;
        Integer perPage = null;
        List<SummaryAthleteDto> response = api.getKudoersByActivityId(id, page, perPage);

        // TODO: test validations
    }
    
    /**
     * List Activity Laps
     *
     * Returns the laps of an activity identified by an identifier. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLapsByActivityIdTest() {
        Long id = null;
        List<LapDto> response = api.getLapsByActivityId(id);

        // TODO: test validations
    }
    
    /**
     * List Athlete Activities
     *
     * Returns the activities of an athlete for a specific identifier. Requires activity:read. Only Me activities will be filtered out unless requested by a token with activity:read_all.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLoggedInAthleteActivitiesTest() {
        Integer before = null;
        Integer after = null;
        Integer page = null;
        Integer perPage = null;
        List<SummaryActivityDto> response = api.getLoggedInAthleteActivities(before, after, page, perPage);

        // TODO: test validations
    }
    
    /**
     * Get Activity Zones
     *
     * Summit Feature. Returns the zones of a given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getZonesByActivityIdTest() {
        Long id = null;
        List<ActivityZoneDto> response = api.getZonesByActivityId(id);

        // TODO: test validations
    }
    
    /**
     * Update Activity
     *
     * Updates the given activity that is owned by the authenticated athlete. Requires activity:write. Also requires activity:read_all in order to update Only Me activities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateActivityByIdTest() {
        Long id = null;
        UpdatableActivityDto body = null;
        DetailedActivityDto response = api.updateActivityById(id, body);

        // TODO: test validations
    }
    
}
