/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.api;

import com.baloise.open.strava.client.model.ActivityStatsDto;
import com.baloise.open.strava.client.model.DetailedAthleteDto;
import com.baloise.open.strava.client.model.FaultDto;
import com.baloise.open.strava.client.model.ZonesDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AthletesApi
 */
@Ignore
public class AthletesApiTest {

    private final AthletesApi api = new AthletesApi();

    
    /**
     * Get Authenticated Athlete
     *
     * Returns the currently authenticated athlete. Tokens with profile:read_all scope will receive a detailed athlete representation; all others will receive a summary representation.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLoggedInAthleteTest() {
        DetailedAthleteDto response = api.getLoggedInAthlete();

        // TODO: test validations
    }
    
    /**
     * Get Zones
     *
     * Returns the the authenticated athlete&#39;s heart rate and power zones. Requires profile:read_all.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLoggedInAthleteZonesTest() {
        ZonesDto response = api.getLoggedInAthleteZones();

        // TODO: test validations
    }
    
    /**
     * Get Athlete Stats
     *
     * Returns the activity stats of an athlete. Only includes data from activities set to Everyone visibilty.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatsTest() {
        Long id = null;
        ActivityStatsDto response = api.getStats(id);

        // TODO: test validations
    }
    
    /**
     * Update Athlete
     *
     * Update the currently authenticated athlete. Requires profile:write scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateLoggedInAthleteTest() {
        Float weight = null;
        DetailedAthleteDto response = api.updateLoggedInAthlete(weight);

        // TODO: test validations
    }
    
}
