/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.api;

import com.baloise.open.strava.client.model.DetailedSegmentEffortDto;
import com.baloise.open.strava.client.model.FaultDto;
import java.time.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SegmentEffortsApi
 */
@Ignore
public class SegmentEffortsApiTest {

    private final SegmentEffortsApi api = new SegmentEffortsApi();

    
    /**
     * List Segment Efforts
     *
     * Returns a set of the authenticated athlete&#39;s segment efforts for a given segment.  Requires subscription.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEffortsBySegmentIdTest() {
        Integer segmentId = null;
        OffsetDateTime startDateLocal = null;
        OffsetDateTime endDateLocal = null;
        Integer perPage = null;
        List<DetailedSegmentEffortDto> response = api.getEffortsBySegmentId(segmentId, startDateLocal, endDateLocal, perPage);

        // TODO: test validations
    }
    
    /**
     * Get Segment Effort
     *
     * Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSegmentEffortByIdTest() {
        Long id = null;
        DetailedSegmentEffortDto response = api.getSegmentEffortById(id);

        // TODO: test validations
    }
    
}
