/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.baloise.open.strava.client.model.DetailedGearAllOfDto;
import com.baloise.open.strava.client.model.SummaryGearDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DetailedGearDto
 */
@JsonPropertyOrder({
  DetailedGearDto.JSON_PROPERTY_ID,
  DetailedGearDto.JSON_PROPERTY_RESOURCE_STATE,
  DetailedGearDto.JSON_PROPERTY_PRIMARY,
  DetailedGearDto.JSON_PROPERTY_NAME,
  DetailedGearDto.JSON_PROPERTY_DISTANCE,
  DetailedGearDto.JSON_PROPERTY_BRAND_NAME,
  DetailedGearDto.JSON_PROPERTY_MODEL_NAME,
  DetailedGearDto.JSON_PROPERTY_FRAME_TYPE,
  DetailedGearDto.JSON_PROPERTY_DESCRIPTION
})
@JsonTypeName("DetailedGear")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-30T10:08:10.913426500+01:00[Europe/Zurich]")
public class DetailedGearDto {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_RESOURCE_STATE = "resource_state";
  private Integer resourceState;

  public static final String JSON_PROPERTY_PRIMARY = "primary";
  private Boolean primary;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DISTANCE = "distance";
  private Float distance;

  public static final String JSON_PROPERTY_BRAND_NAME = "brand_name";
  private String brandName;

  public static final String JSON_PROPERTY_MODEL_NAME = "model_name";
  private String modelName;

  public static final String JSON_PROPERTY_FRAME_TYPE = "frame_type";
  private Integer frameType;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;


  public DetailedGearDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The gear&#39;s unique identifier.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The gear's unique identifier.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public DetailedGearDto resourceState(Integer resourceState) {
    
    this.resourceState = resourceState;
    return this;
  }

   /**
   * Resource state, indicates level of detail. Possible values: 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot;
   * @return resourceState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Resource state, indicates level of detail. Possible values: 2 -> \"summary\", 3 -> \"detail\"")
  @JsonProperty(JSON_PROPERTY_RESOURCE_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getResourceState() {
    return resourceState;
  }


  public void setResourceState(Integer resourceState) {
    this.resourceState = resourceState;
  }


  public DetailedGearDto primary(Boolean primary) {
    
    this.primary = primary;
    return this;
  }

   /**
   * Whether this gear&#39;s is the owner&#39;s default one.
   * @return primary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether this gear's is the owner's default one.")
  @JsonProperty(JSON_PROPERTY_PRIMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPrimary() {
    return primary;
  }


  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }


  public DetailedGearDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The gear&#39;s name.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The gear's name.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DetailedGearDto distance(Float distance) {
    
    this.distance = distance;
    return this;
  }

   /**
   * The distance logged with this gear.
   * @return distance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The distance logged with this gear.")
  @JsonProperty(JSON_PROPERTY_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getDistance() {
    return distance;
  }


  public void setDistance(Float distance) {
    this.distance = distance;
  }


  public DetailedGearDto brandName(String brandName) {
    
    this.brandName = brandName;
    return this;
  }

   /**
   * The gear&#39;s brand name.
   * @return brandName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The gear's brand name.")
  @JsonProperty(JSON_PROPERTY_BRAND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBrandName() {
    return brandName;
  }


  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }


  public DetailedGearDto modelName(String modelName) {
    
    this.modelName = modelName;
    return this;
  }

   /**
   * The gear&#39;s model name.
   * @return modelName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The gear's model name.")
  @JsonProperty(JSON_PROPERTY_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModelName() {
    return modelName;
  }


  public void setModelName(String modelName) {
    this.modelName = modelName;
  }


  public DetailedGearDto frameType(Integer frameType) {
    
    this.frameType = frameType;
    return this;
  }

   /**
   * The gear&#39;s frame type (bike only).
   * @return frameType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The gear's frame type (bike only).")
  @JsonProperty(JSON_PROPERTY_FRAME_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFrameType() {
    return frameType;
  }


  public void setFrameType(Integer frameType) {
    this.frameType = frameType;
  }


  public DetailedGearDto description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The gear&#39;s description.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The gear's description.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedGearDto detailedGear = (DetailedGearDto) o;
    return Objects.equals(this.id, detailedGear.id) &&
        Objects.equals(this.resourceState, detailedGear.resourceState) &&
        Objects.equals(this.primary, detailedGear.primary) &&
        Objects.equals(this.name, detailedGear.name) &&
        Objects.equals(this.distance, detailedGear.distance) &&
        Objects.equals(this.brandName, detailedGear.brandName) &&
        Objects.equals(this.modelName, detailedGear.modelName) &&
        Objects.equals(this.frameType, detailedGear.frameType) &&
        Objects.equals(this.description, detailedGear.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, resourceState, primary, name, distance, brandName, modelName, frameType, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedGearDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resourceState: ").append(toIndentedString(resourceState)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    frameType: ").append(toIndentedString(frameType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

