/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * SummaryPRSegmentEffortDto
 */
@JsonPropertyOrder({
  SummaryPRSegmentEffortDto.JSON_PROPERTY_PR_ACTIVITY_ID,
  SummaryPRSegmentEffortDto.JSON_PROPERTY_PR_ELAPSED_TIME,
  SummaryPRSegmentEffortDto.JSON_PROPERTY_PR_DATE,
  SummaryPRSegmentEffortDto.JSON_PROPERTY_EFFORT_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-01T17:37:53.710209+01:00[Europe/Zurich]")
public class SummaryPRSegmentEffortDto {
  public static final String JSON_PROPERTY_PR_ACTIVITY_ID = "pr_activity_id";
  private Long prActivityId;

  public static final String JSON_PROPERTY_PR_ELAPSED_TIME = "pr_elapsed_time";
  private Integer prElapsedTime;

  public static final String JSON_PROPERTY_PR_DATE = "pr_date";
  private OffsetDateTime prDate;

  public static final String JSON_PROPERTY_EFFORT_COUNT = "effort_count";
  private Integer effortCount;


  public SummaryPRSegmentEffortDto prActivityId(Long prActivityId) {
    
    this.prActivityId = prActivityId;
    return this;
  }

   /**
   * The unique identifier of the activity related to the PR effort.
   * @return prActivityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique identifier of the activity related to the PR effort.")
  @JsonProperty(JSON_PROPERTY_PR_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPrActivityId() {
    return prActivityId;
  }


  public void setPrActivityId(Long prActivityId) {
    this.prActivityId = prActivityId;
  }


  public SummaryPRSegmentEffortDto prElapsedTime(Integer prElapsedTime) {
    
    this.prElapsedTime = prElapsedTime;
    return this;
  }

   /**
   * The elapsed time ot the PR effort.
   * @return prElapsedTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The elapsed time ot the PR effort.")
  @JsonProperty(JSON_PROPERTY_PR_ELAPSED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPrElapsedTime() {
    return prElapsedTime;
  }


  public void setPrElapsedTime(Integer prElapsedTime) {
    this.prElapsedTime = prElapsedTime;
  }


  public SummaryPRSegmentEffortDto prDate(OffsetDateTime prDate) {
    
    this.prDate = prDate;
    return this;
  }

   /**
   * The time at which the PR effort was started.
   * @return prDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time at which the PR effort was started.")
  @JsonProperty(JSON_PROPERTY_PR_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPrDate() {
    return prDate;
  }


  public void setPrDate(OffsetDateTime prDate) {
    this.prDate = prDate;
  }


  public SummaryPRSegmentEffortDto effortCount(Integer effortCount) {
    
    this.effortCount = effortCount;
    return this;
  }

   /**
   * Number of efforts by the authenticated athlete on this segment.
   * @return effortCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of efforts by the authenticated athlete on this segment.")
  @JsonProperty(JSON_PROPERTY_EFFORT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEffortCount() {
    return effortCount;
  }


  public void setEffortCount(Integer effortCount) {
    this.effortCount = effortCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryPRSegmentEffortDto summaryPRSegmentEffort = (SummaryPRSegmentEffortDto) o;
    return Objects.equals(this.prActivityId, summaryPRSegmentEffort.prActivityId) &&
        Objects.equals(this.prElapsedTime, summaryPRSegmentEffort.prElapsedTime) &&
        Objects.equals(this.prDate, summaryPRSegmentEffort.prDate) &&
        Objects.equals(this.effortCount, summaryPRSegmentEffort.effortCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prActivityId, prElapsedTime, prDate, effortCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryPRSegmentEffortDto {\n");
    sb.append("    prActivityId: ").append(toIndentedString(prActivityId)).append("\n");
    sb.append("    prElapsedTime: ").append(toIndentedString(prElapsedTime)).append("\n");
    sb.append("    prDate: ").append(toIndentedString(prDate)).append("\n");
    sb.append("    effortCount: ").append(toIndentedString(effortCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

