/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baloise.open.strava.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.baloise.open.strava.client.model.ActivityTypeDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * UpdatableActivityDto
 */
@JsonPropertyOrder({
  UpdatableActivityDto.JSON_PROPERTY_COMMUTE,
  UpdatableActivityDto.JSON_PROPERTY_TRAINER,
  UpdatableActivityDto.JSON_PROPERTY_HIDE_FROM_HOME,
  UpdatableActivityDto.JSON_PROPERTY_DESCRIPTION,
  UpdatableActivityDto.JSON_PROPERTY_NAME,
  UpdatableActivityDto.JSON_PROPERTY_TYPE,
  UpdatableActivityDto.JSON_PROPERTY_GEAR_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-01T17:37:53.710209+01:00[Europe/Zurich]")
public class UpdatableActivityDto {
  public static final String JSON_PROPERTY_COMMUTE = "commute";
  private Boolean commute;

  public static final String JSON_PROPERTY_TRAINER = "trainer";
  private Boolean trainer;

  public static final String JSON_PROPERTY_HIDE_FROM_HOME = "hide_from_home";
  private Boolean hideFromHome;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_TYPE = "type";
  private ActivityTypeDto type;

  public static final String JSON_PROPERTY_GEAR_ID = "gear_id";
  private String gearId;


  public UpdatableActivityDto commute(Boolean commute) {
    
    this.commute = commute;
    return this;
  }

   /**
   * Whether this activity is a commute
   * @return commute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether this activity is a commute")
  @JsonProperty(JSON_PROPERTY_COMMUTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCommute() {
    return commute;
  }


  public void setCommute(Boolean commute) {
    this.commute = commute;
  }


  public UpdatableActivityDto trainer(Boolean trainer) {
    
    this.trainer = trainer;
    return this;
  }

   /**
   * Whether this activity was recorded on a training machine
   * @return trainer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether this activity was recorded on a training machine")
  @JsonProperty(JSON_PROPERTY_TRAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrainer() {
    return trainer;
  }


  public void setTrainer(Boolean trainer) {
    this.trainer = trainer;
  }


  public UpdatableActivityDto hideFromHome(Boolean hideFromHome) {
    
    this.hideFromHome = hideFromHome;
    return this;
  }

   /**
   * Whether this activity is muted
   * @return hideFromHome
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether this activity is muted")
  @JsonProperty(JSON_PROPERTY_HIDE_FROM_HOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHideFromHome() {
    return hideFromHome;
  }


  public void setHideFromHome(Boolean hideFromHome) {
    this.hideFromHome = hideFromHome;
  }


  public UpdatableActivityDto description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The description of the activity
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The description of the activity")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public UpdatableActivityDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the activity
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the activity")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public UpdatableActivityDto type(ActivityTypeDto type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivityTypeDto getType() {
    return type;
  }


  public void setType(ActivityTypeDto type) {
    this.type = type;
  }


  public UpdatableActivityDto gearId(String gearId) {
    
    this.gearId = gearId;
    return this;
  }

   /**
   * Identifier for the gear associated with the activity. ‘none’ clears gear from activity
   * @return gearId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifier for the gear associated with the activity. ‘none’ clears gear from activity")
  @JsonProperty(JSON_PROPERTY_GEAR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGearId() {
    return gearId;
  }


  public void setGearId(String gearId) {
    this.gearId = gearId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatableActivityDto updatableActivity = (UpdatableActivityDto) o;
    return Objects.equals(this.commute, updatableActivity.commute) &&
        Objects.equals(this.trainer, updatableActivity.trainer) &&
        Objects.equals(this.hideFromHome, updatableActivity.hideFromHome) &&
        Objects.equals(this.description, updatableActivity.description) &&
        Objects.equals(this.name, updatableActivity.name) &&
        Objects.equals(this.type, updatableActivity.type) &&
        Objects.equals(this.gearId, updatableActivity.gearId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commute, trainer, hideFromHome, description, name, type, gearId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatableActivityDto {\n");
    sb.append("    commute: ").append(toIndentedString(commute)).append("\n");
    sb.append("    trainer: ").append(toIndentedString(trainer)).append("\n");
    sb.append("    hideFromHome: ").append(toIndentedString(hideFromHome)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    gearId: ").append(toIndentedString(gearId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

